[package]
name = "rayengine-cli"
description = "Project tools for rayengine games"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
documentation = "https://docs.rs/rayengine-cli"
keywords = ["game", "raylib", "cli"]
categories = ["command-line-utilities", "development-tools"]
include = ["Cargo.toml", "README.md", "LICENSE", "src/**", "docs/**", "examples/**", "benches/**", "tests/**"]

[[bin]]
name = "rayengine"
path = "src/main.rs"
doc = false

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
rayengine-core.workspace = true

[lints]
workspace = true
