[package]
name = "rayengine-cli"
description = "Project tools for rayengine games"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rayengine"
path = "src/main.rs"
doc = false

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
