//! Original skinned character: a lamplighter walks between two lanterns and
//! waves to light each one. Run with `cargo run -p rayengine --example character`.
//! The glTF asset is generated by `scripts/generate_character_model.py`.
use rayengine::{core::skeletal::KeyframeRate, prelude::*};
use std::{f32::consts::FRAC_PI_2, time::Duration};

const CHARACTER: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/examples/assets/character.glb");
const LEFT: Action = Action(0);
const RIGHT: Action = Action(1);
const INTERACT: Action = Action(2);
const PAUSE: Action = Action(3);
const RESET: Action = Action(4);
const LANTERNS: [f32; 2] = [-3.0, 3.0];
/// Where the lamplighter stands to reach a lantern.
const REACH: f32 = 0.9;
const SPEED: f32 = 1.6;

/// Fresh players are `Copy`; switching clips copies one in at its first keyframe.
struct Clips {
    idle: ModelAnimator,
    walk: ModelAnimator,
    wave: ModelAnimator,
}

struct Lamplighter {
    model: Option<ModelId>,
    clips: Option<Clips>,
    animator: Option<ModelAnimator>,
    x: f32,
    previous_x: f32,
    heading: f32,
    lit: [bool; 2],
    target: usize,
    manual: bool,
}

impl Lamplighter {
    fn new() -> Self {
        Self {
            model: None,
            clips: None,
            animator: None,
            x: 0.0,
            previous_x: 0.0,
            heading: 1.0,
            lit: [false; 2],
            target: 1,
            manual: false,
        }
    }
    fn select(&mut self, clip: ModelClipId) {
        let clips = self.clips.as_ref().unwrap();
        let animator = self.animator.as_mut().unwrap();
        if animator.clip() != clip {
            *animator = [clips.idle, clips.walk, clips.wave]
                .into_iter()
                .find(|fresh| fresh.clip() == clip)
                .unwrap();
        }
    }
    fn lantern_in_reach(&self) -> Option<usize> {
        LANTERNS
            .iter()
            .position(|&lantern| (lantern - self.x).abs() <= REACH + 0.05)
    }
}

impl Game for Lamplighter {
    fn bindings(&self) -> Bindings {
        Bindings::new()
            .bind(LEFT, KeyboardKey::KEY_A)
            .bind(LEFT, KeyboardKey::KEY_LEFT)
            .bind(RIGHT, KeyboardKey::KEY_D)
            .bind(RIGHT, KeyboardKey::KEY_RIGHT)
            .bind(INTERACT, KeyboardKey::KEY_E)
            .bind(PAUSE, KeyboardKey::KEY_P)
            .bind(RESET, KeyboardKey::KEY_R)
    }

    fn init(&mut self, context: &mut InitContext<'_, '_>) -> Result<(), Error> {
        let model = context.model(CHARACTER)?;
        let set = context.model_animations(CHARACTER, KeyframeRate::GLTF)?;
        let clip = |name| {
            context
                .assets
                .find_model_clip(set, name)
                .ok_or_else(|| Error::Asset(format!("character has no {name} clip")))
        };
        let (idle, walk, wave) = (clip("idle")?, clip("walk")?, clip("wave")?);
        // model_animator checks skeleton compatibility once, up front.
        let assets = &context.assets;
        let clips = Clips {
            idle: assets.model_animator(model, idle, PlaybackMode::Loop)?,
            walk: assets.model_animator(model, walk, PlaybackMode::Loop)?,
            wave: assets.model_animator(model, wave, PlaybackMode::Once)?,
        };
        self.animator = Some(clips.walk);
        self.clips = Some(clips);
        self.model = Some(model);
        Ok(())
    }

    fn fixed_update(&mut self, context: &mut Update<'_, '_>) {
        let input = context.input;
        if input.pressed(RESET) {
            let model = self.model;
            let clips = self.clips.take();
            *self = Self::new();
            self.model = model;
            self.animator = clips.as_ref().map(|c| c.walk);
            self.clips = clips;
        }
        let clips = self.clips.as_ref().unwrap();
        let (idle, walk, wave) = (clips.idle.clip(), clips.walk.clip(), clips.wave.clip());
        let animator = self.animator.as_mut().unwrap();
        if input.pressed(PAUSE) {
            if animator.is_paused() {
                animator.resume();
            } else {
                animator.pause();
            }
        }
        self.previous_x = self.x;
        if animator.is_paused() {
            return;
        }
        let dt = context.tick.dt;
        let direction = input.axis(LEFT, RIGHT);
        if direction != 0.0 {
            self.manual = true;
        }
        if animator.clip() == wave {
            // Movement waits for the interaction clip, whose completion is reported once.
        } else if self.manual {
            self.x = (self.x + direction * SPEED * dt).clamp(-4.5, 4.5);
            if direction != 0.0 {
                self.heading = direction.signum();
            }
            if input.pressed(INTERACT) && self.lantern_in_reach().is_some() {
                self.select(wave);
            } else {
                self.select(if direction == 0.0 { idle } else { walk });
            }
        } else {
            // Autopilot: walk to the unlit lantern, stop within reach, then wave.
            let goal = LANTERNS[self.target] - REACH * (LANTERNS[self.target] - self.x).signum();
            let step = SPEED * dt;
            if (goal - self.x).abs() <= step {
                self.x = goal;
                self.select(wave);
            } else {
                self.heading = (goal - self.x).signum();
                self.x += self.heading * step;
                self.select(walk);
            }
        }
        let animator = self.animator.as_mut().unwrap();
        if animator.advance(Duration::from_secs_f32(dt)).is_some() {
            if let Some(lantern) = self.lantern_in_reach() {
                // Lighting one lantern douses the other so the round trip continues.
                self.lit = [lantern == 0, lantern == 1];
                self.target = 1 - lantern;
            }
            self.select(if self.manual { idle } else { walk });
        }
    }

    fn draw(&mut self, frame: &mut Frame<'_, '_>) {
        frame.clear(Color::new(20, 24, 40, 255));
        let x = self.previous_x + (self.x - self.previous_x) * frame.alpha;
        let camera = Camera3D {
            position: Vec3::new(0.0, 2.6, 7.5),
            target: Vec3::new(0.0, 1.0, 0.0),
            ..Camera3D::default()
        };
        let (Some(model), Some(animator)) = (self.model, self.animator) else {
            return;
        };
        let walking = self
            .clips
            .as_ref()
            .is_some_and(|c| animator.clip() == c.walk.clip());
        frame.world_3d(camera, |canvas| {
            canvas.cube(
                Aabb3::from_center(Vec3::new(0.0, -0.05, 0.0), Vec3::new(11.0, 0.1, 3.0)),
                Color::new(54, 84, 64, 255),
            );
            for (lantern, lit) in LANTERNS.into_iter().zip(self.lit) {
                canvas.cube(
                    Aabb3::from_center(Vec3::new(lantern, 1.0, -0.4), Vec3::new(0.12, 2.0, 0.12)),
                    Color::new(70, 60, 54, 255),
                );
                let glow = if lit { Color::GOLD } else { Color::DARKGRAY };
                canvas.sphere(Vec3::new(lantern, 2.15, -0.4), 0.22, glow);
            }
            // Face the walking direction, or the viewer while waving or idle.
            let facing = if walking {
                Quat::from_rotation_y(FRAC_PI_2 * self.heading)
            } else {
                Quat::IDENTITY
            };
            canvas.animated_model(
                model,
                animator,
                Transform3D {
                    position: Vec3::new(x, 0.0, 0.0),
                    rotation: facing,
                    ..Transform3D::default()
                },
                Color::WHITE,
            );
        });
        frame.ui(|ui| {
            ui.text(
                "A/D walk   E wave at a lantern   P pause   R restart",
                Vec2::new(16.0, 16.0),
                18.0,
                Color::WHITE,
            );
            let name = self
                .clips
                .as_ref()
                .map(|c| {
                    if animator.clip() == c.wave.clip() {
                        "wave"
                    } else if animator.clip() == c.walk.clip() {
                        "walk"
                    } else {
                        "idle"
                    }
                })
                .unwrap_or_default();
            ui.text(
                &format!(
                    "{name} keyframe {:.1}{}",
                    animator.keyframe(),
                    if animator.is_paused() {
                        " (paused)"
                    } else {
                        ""
                    }
                ),
                Vec2::new(16.0, 42.0),
                18.0,
                Color::GOLD,
            );
        });
    }
}

fn main() -> Result<(), Error> {
    let config = Config::new("rayengine / Character animation");
    App::new(config)
        .with_options(RunOptions::from_env()?)
        .run(Lamplighter::new())?;
    Ok(())
}
